import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import YAML from "yaml";

const projectRoot = resolve(import.meta.dirname, "..");
const dataRoot = resolve(projectRoot, "data/decks");
const outputPath = resolve(projectRoot, "app/data/cards.generated.ts");

const categoryMetadata = {
  animals: { title: "Animali", icon: "paw" },
  body: { title: "Corpo umano", icon: "person" },
  children: { title: "Bambini", icon: "child-reaching" },
  brand: { title: "Brand", icon: "tag" },
  cartoon: { title: "Cartoni", icon: "film" },
  food: { title: "Cibo", icon: "utensils" },
  house: { title: "Casa", icon: "house" },
  jobs: { title: "Mestieri", icon: "briefcase" },
  daily: { title: "Vita quotidiana", icon: "calendar-day" },
  geo: { title: "Geografia", icon: "earth-europe" },
  math: { title: "Matematica", icon: "calculator" },
  music: { title: "Musica", icon: "music" },
  nature: { title: "Natura", icon: "leaf" },
  nerd: { title: "Nerd", icon: "gamepad" },
  science: { title: "Scienza", icon: "flask" },
  sport: { title: "Sport", icon: "futbol" },
  history: { title: "Storia", icon: "landmark" },
  tech: { title: "Tecnologia", icon: "microchip" },
  holiday: { title: "Vacanze", icon: "umbrella-beach" },
  vehicoles: { title: "Veicoli", icon: "car-side" },
  vip: { title: "Personaggi famosi", icon: "star" },
};

const normalize = (value) =>
  value.normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("it");

const duplicateKey = (value) =>
  normalize(value)
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9]/g, "");

const slugify = (value) =>
  normalize(value)
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const hash = (value) => {
  let result = 2166136261;
  for (const char of value) {
    result ^= char.charCodeAt(0);
    result = Math.imul(result, 16777619);
  }
  return (result >>> 0).toString(36);
};

const files = (await readdir(dataRoot))
  .filter((file) => file.endsWith(".yaml"))
  .sort();
const cards = [];
const errors = [];
const normalizedWords = new Map();

for (const file of files) {
  const categoryId = file.replace(/\.yaml$/, "");
  const metadata = categoryMetadata[categoryId];
  if (!metadata) {
    errors.push(`${file}: categoria sconosciuta`);
    continue;
  }

  const source = await readFile(resolve(dataRoot, file), "utf8");
  const document = YAML.parseDocument(source, { uniqueKeys: true });
  if (document.errors.length) {
    for (const error of document.errors) errors.push(`${file}: ${error.message}`);
    continue;
  }

  const entries = Object.entries(document.toJS() ?? {});
  for (const [rawWord, rawForbidden] of entries) {
    const word = String(rawWord).trim();
    const key = normalize(word);
    const deduplicationKey = duplicateKey(word);

    if (normalizedWords.has(deduplicationKey)) {
      errors.push(
        `${file}: "${word}" duplica ${normalizedWords.get(deduplicationKey)} dopo la normalizzazione`,
      );
      continue;
    }
    normalizedWords.set(deduplicationKey, `${file}:"${word}"`);

    if (!Array.isArray(rawForbidden) || rawForbidden.length !== 5) {
      errors.push(`${file}: "${word}" deve avere esattamente 5 parole vietate`);
      continue;
    }

    const forbidden = rawForbidden.map((item) => String(item).trim());
    if (forbidden.some((item) => !item)) {
      errors.push(`${file}: "${word}" contiene una parola vietata vuota`);
    }

    const normalizedForbidden = forbidden.map(normalize);
    if (new Set(normalizedForbidden).size !== forbidden.length) {
      errors.push(`${file}: "${word}" contiene parole vietate duplicate`);
    }
    if (normalizedForbidden.includes(key)) {
      errors.push(`${file}: "${word}" compare anche tra le parole vietate`);
    }

    cards.push({
      id: `${slugify(word) || "carta"}-${hash(key)}`,
      word,
      forbidden,
      categoryId,
    });
  }
}

if (errors.length) {
  console.error(`Database non valido (${errors.length} errori):`);
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

const categories = Object.entries(categoryMetadata).map(([id, metadata]) => ({
  id,
  ...metadata,
  count: cards.filter((card) => card.categoryId === id).length,
}));

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `/* Generated by scripts/build-decks.mjs. Do not edit manually. */\n` +
    `import type { Card, Category } from "../lib/types";\n\n` +
    `export const categories: Category[] = ${JSON.stringify(categories)};\n\n` +
    `export const cards: Card[] = ${JSON.stringify(cards)};\n`,
);

console.log(`Database valido: ${cards.length} carte in ${categories.length} mazzi.`);
